AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.kimulimul::serverless
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kimulimuli.serverless.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/serverless-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  GreetingApi:
    Description: URL for application
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greeting"
    Export:
      Name: GreetingApi
